config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }
  get 'artists/index'
  root 'artists#index'
  resources :artists do 
    resources :comments
  end
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/artist.rb
$maxwidthheightratio = 1.7
$maxheightwidthratio = 3

class Artist < ApplicationRecord
    has_many :comments
    validates :name, :image_url, presence: true
    validate :checkImage
    def checkImage
        if(FastImage.type(image_url)==nil)  
            errors.add(:image_url," is not an image")
            return
        end
        width=FastImage.size(image_url)[0]
        height=FastImage.size(image_url)[1]
        if(width>$maxwidthheightratio*height) 
            errors.add(:image_width, "is too much higher than Height") 
            return
        end
        if(height>$maxheightwidthratio*width) 
            errors.add(:image_height, "is too much higher than Width") 
            return
        end
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description, :country_of_origin, :image_url)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<div class="center">
  <%= bootstrap_form_for(artist) do |f| %>
    <% if artist.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(artist.errors.count, "error") %> prohibited this character from being saved:</h2>
        <ul>
        <% artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="jumbotron bg3">
      <h1 class="display-1 center"><%= action_name.capitalize%> Character</h1>
      <p class="lead"><%= action_name.capitalize%> Mythological character!</p>
    </div>
    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <small>Insert the country of origin of the legend to see it marked in map <a href="https://fusiontables.google.com/data?docid=1N2LBk4JHwWpOY4d9fobIn27lfnZ5MDy-NoqqRpk&pli=1#rows:id=1">(Search here if you are unsure about the name)</a> </small>
    <%= f.text_field :country_of_origin %>
    <%= f.url_field :image_url %>
    <div class="btn-group btn-group-lg" role="group" aria-label="...">
      <%= f.submit action_name.capitalize+" Character"%>
      <%= link_to 'Back', artists_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/artists/edit.html.erb
<%= render 'form', artist: @artist %>

app/views/artists/index.html.erb
<div class="jumbotron bg3">
  <h1 class="center">Mythological Database</h1>
  <h2 class="center">Mythological characters database, with bit of story and the place where they where invented</h2>
</div>
<div class="row fixed">
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg1 center cell "><h2>Image</h2></div>
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg3 center cell "><h2>Name</h2></div>
  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 bg1 center cell "><h2>Description</h2></div>
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bg3 center cell "><% if user_signed_in? %><h2>Edit</h2><% end %></div>
</div>
<% @artists.each do |artist|%>
  <div class="row fixed">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 <%= cycle('bg3','bg2','bg3','bg2','bg1','bg3', 'bg1', 'bg3')%> center cell">
      <%= link_to '<img width="100%" src="'.html_safe+artist.image_url+'"/>'.html_safe, artist %><br></div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 <%= cycle('bg3','bg2','bg3','bg2','bg1','bg3', 'bg1', 'bg3')%> center cell ">
       <%= link_to artist.name, artist %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 center cell <%= cycle('bg3','bg2','bg3','bg2','bg1','bg3', 'bg1', 'bg3')%> ">
      <%= artist.description.length<1000 ? artist.description.html_safe : artist.description[0,200]+'...' %>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 <%= cycle('bg3','bg2','bg3','bg2','bg1','bg3', 'bg1', 'bg3')%> cell center">
      <% if user_signed_in? %>
        <div class="btn-group-vertical">
          <%= link_to 'Edit', edit_artist_path(artist), class: 'btn btn-outline-primary' %><br>
          <%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'%>
        </div>
      <% end %>
    </div>
  </div>  
  <% end %>
<br>
<div class="center">
  <% if user_signed_in? %>
    <%= link_to 'New Artist', new_artist_path, class:'btn btn-primary' %>
  <% end %>
</div>

app/views/artists/new.html.erb
<%= render 'form', artist: @artist %>

app/views/artists/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2></h2></div>
  <div class="panel-body"> 
  </div>
</div>
<div class="col-lg-3 col-md-2 col-sm-1 hidden-sm"></div>
<div class="card col-lg-6 col-md-8 col-sm-10 col-sm-12 bg4">
  <div class="card-block center">
    <h2 class="card-title"><%= @artist.name %></h2>
  </div>
  <img class="img-fluid center" src="<%= @artist.image_url %>" alt="<%= @artist.name %>">
  <div class="card-block center">
    <%= @artist.description.html_safe %>
  </div>
  <div class="card-block center square" id="map">
  </div>
  <script>
      var marker={};
      var map={};
      var countries,country_vector,country_string;
      function waitALittle(){
        countries = <%= '"'.html_safe+ @artist.country_of_origin+'"'.html_safe %>;
        country_vector = countries.split(", ");
        //generating the string that will be used for the query 
        country_string = "'"+country_vector[0];
        for (var i=1; i<country_vector.length; i++) {
          country_string +="','"+country_vector[i];
        }
        country_string +="'";
        //map
        map = new google.maps.Map(document.getElementById('map'), {
          center: new google.maps.LatLng(30,0),
          zoom: 6,
          streetViewControl: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        map.markers = [];
        var world_geometry = new google.maps.FusionTablesLayer({
            query: {
            select: 'geometry',
            from: '1N2LBk4JHwWpOY4d9fobIn27lfnZ5MDy-NoqqRpk',
            where: "Name IN ("+country_string+")"
          },
          map: map,
          suppressInfoWindows: true
        });
        var geocoder = new google.maps.Geocoder();
        for (var i=0; i<country_vector.length; i++) {
          geocoder.geocode( {'address' : country_vector[i]}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              marker = new google.maps.Marker({position: results[0].geometry.location,map: map});
              map.markers.push(marker);
              google.maps.event.trigger(map, 'resize');
              center();
            }
          }
        );
      }
    }
    function center(){
      map.setCenter(marker.position);
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5XyFato2vOwJzdw1PcOlk__hm6tAVEuc&callback=waitALittle" async defer ></script>
  <div class="card-block center" id="there">
    <small>Press "Center" after map is loaded</small><br/>
    <% if user_signed_in? %>
    <%= link_to 'Destroy', @artist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'%>|
    <%= link_to 'Edit', edit_artist_path(@artist), class: "btn btn-primary" %>|
    <% end %>
    <button type="button" class="btn btn-info" onclick="center()">Center</button>|
    <%= link_to 'Back', artists_path, class: "btn btn-secondary" %>
  </div>
  <div class="jumbotron bg3">
    <h1 class="center">Comments</h1>
    <h2 class="center">List of comments to the character</h2>
  </div>
  <% if user_signed_in? %>
    <%= bootstrap_form_for [@artist, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a comment" %><br/>
      <%= f.hidden_field :user_id, value: current_user %>
      <%= f.submit "Add Comment" %>
    <% end %>
  <% end %>
  <br/>
  <ul class="list-group">
    <%= render(partial: 'comments/comment', collection: @artist.comments) %>
  </ul>
</div>